### ISSUE TITLE
Retina Support?

### ISSUE THREAD

**Issue by ServusJon** [littlebusters/Sketch-CSS-Sprite-Mixin#3]
What a great plugin! Could you please extend it that it supports retina sprites as well?

Thank you!

**Comment by littlebusters** [comment]
I can't promise anything, but I'll extend at next update.

https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png

**Comment by BliztRipper** [comment]
Can you explain how to use it in real project cuz i'm so confuse with the css variable

Thanks you

**Comment by ServusJon** [comment]
@BliztRipper you can use this: https://github.com/ServusJon/Sketch-CSS-Sprite-Mixin
