### ISSUE TITLE
Layer names with spaces

### ISSUE THREAD

**Issue by ultrawebsites** [littlebusters/Sketch-CSS-Sprite-Mixin#8]
Hi there - great plugin!

One suggestion, if possible - if there are spaces in the top-level layer names, these should be removed, or replaced with hypens (-) - otherwise, for example, the LESS variable names have spaces in them and are not valid LESS and it can't be compiled (and is a bit confusing at first).

**Comment by littlebusters** [comment]
Thanks for the suggestion.
Merged!
